### ISSUE TITLE
Publish app on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [LukasKnuth/bike-track#1]
Hi Lukas,

it would be nice if you could add it to the [F-Droid repository](https://f-droid.org/repository/browse/).

Thank you very much

**Comment by LukasKnuth** [comment]
I don't consider it's current state anywhere near publishable. And I have no intentions to "finish" it.

Maybe I'll update it at some point in the future. Until then, it's just another hobby project.

**Comment by alexanderadam** [comment]
Okay, no problem. Thank you anyway
